### ISSUE TITLE
Ep 5 first challenge, inconsistency in definition of global variables

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/snakemake-novice-bioinformatics#11]
The first part of the solution has four global variables defined:

```
# Input conditions and replicates to process
CONDITIONS = ["ref", "etoh60", "temp33"]
REPLICATES = ["1", "2", "3"]
READ_ENDS  = ["1", "2"]
COUNT_DIR  = ["reads", "trimmed"]

# Rule to make all counts at once
rule all_counts:
  input: expand("{indir}.{cond}_{rep}_{end}.fq.count", indir=COUNT_DIR, cond=CONDITIONS, rep=REPLICATES, end=READ_ENDS)
```

The second part of the solution only has two global variables defined, with the remaining two variables defined inside the `expand()` function:

```
# Input conditions and replicates to process
CONDITIONS = ["ref", "etoh60", "temp33"]
REPLICATES = ["1", "2", "3"]


# Rule to make all counts at once
rule all_counts:
  input:
    expand( "{indir}.{cond}_{rep}_{end}.fq.count", indir = ["reads", "trimmed"],
                                                   cond  = CONDITIONS,
                                                   rep   = REPLICATES,
                                                   end   = ["1", "2"] )
```

I'm not sure whether this was done consciously, which is why I'm not fixing this through a PR. If this was done to show that variables can also be defined within the `expand` function, perhaps it'd be good to mention this explicitly.

**Comment by ezherman** [comment]
Depending on whether edits are made, the solution to the final challenge of this episode may need to be edited as well, as it currently has two variables that are defined within `expand`.

**Comment by tbooth** [comment]
You can't "define variables within [a function call]" so I certainly don't want to give that impression.

The intention of the two answers it to illustrate that defining named variables for all expand() parameters isn't necessary. My thought is that the first solution is the more obvious one (as it just adds to what we already have) but the second is probably a little neater, and students should appreciate that both achieve the same thing. The idea that you can use an expression instead of a named variable feeds on to later idea (eg. in configuration).

I tried to clarify the text a little just now, but possibly it could be even clearer. As a programmer these things just seem so obvious to me it's sometime hard to know what I need to explain.

**Comment by ezherman** [comment]
Ah yes, that was badly worded on my part. I meant that the lists are specified within the function call, rather than through a global variable. 

I think the updated text does a good job at explaining the alternative option!
