### ISSUE TITLE
symlinks issue multiqc

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries-incubator/snakemake-novice-bioinformatics#23]
The terminal on my Mac does have `ln`, but it does not have the `-r` and `-t` options. This means that this from rule `rule multiqc` in `ep06.Snakefile` does not work:

```
mkdir {output.mqc_in}
ln -snr -t {output.mqc_in} {input}
```

I am struggling to find a workaround. All folders in {input} need a symlink in `multiqc_in`. Apart from using a unix for loop, how could this be done? Or, is there a way to install a version of `ln` that works as intended in the lesson?

The man page says the `ln` version I have is `BSD July 12, 2019` (Mac OS Big Sur 11.6.5)

**Comment by tbooth** [comment]
You could always install Linux on your Mac hardware ;-)

But in seriousness, installing the GNU coreutils on your Mac is probably a good idea, as there are lot of nice enhancements like this, and most online sources of shell help will assume you have the GNU versions. The older option for this was the Homebrew package manager (https://brew.sh/) but since you are already working in a Conda environment it should, I believe, simply be:

```
$ conda install -c conda-forge coreutils
```

Does that work?

**Comment by lexnederbragt** [comment]
It does! This is perfect, thanks!
