### ISSUE TITLE
-n flag used without clarification

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/snakemake-novice-bioinformatics#33]
Minor comment: in episode 5, under ["dynamically determining the inputs"](https://carpentries-incubator.github.io/snakemake-novice-bioinformatics/aio/index.html#dynamically-determining-the-inputs), the `-n` flag is used. However, there is no mention of what the `-n` flag does. This could be clarified, e.g.:

```
$ snakemake -j1 -F -n -p all_counts
Conditions are:  ['etoh60', 'temp33', 'ref']
Building DAG of jobs...
Job counts:
	count	jobs
	1	all_counts
	36	countreads
	18	trimreads
	55
...
```

"Since we have already have created all the output files for `countreads`, as specified by `all_counts`, we need to force Snakemake to re-create these files using the `-F` flag. As we are only interested in testing the ability of our `CONDITIONS` variable to direct the `all_counts` rule, we do not want Snakemake to re-run the jobs. To prevent Snakemake from executing the jobs, we include the `-n` flag. This specifies a so-called "dry run": Snakemake shows us the jobs that it would execute, if this were a regular run."

**Comment by tbooth** [comment]
Hmm. I'm sure that at some point in time the `-n` flag was introduced properly in an earlier episode, but you are right it just appears here with no explanation. I think there should be a proper mention of it, maybe as early as episode 2 - it seems to fit in here:

https://carpentries-incubator.github.io/snakemake-novice-bioinformatics/02-placeholders/index.html#snakemake-order-of-operations
Because `-n` basically means "stop after phase 2".

I'll hopefully have time on Monday to do a quick edit before you teach on Tuesday. Thanks for spotting this.

**Comment by ezherman** [comment]
Thanks for looking into this Tim, your suggested solution sounds good to me!
